# Generated by Django 5.1.4 on 2026-09-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('created_by', models.CharField(max_length=64, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QueryArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_keyword', models.CharField(max_length=200, verbose_name='查询字')),
                ('verdict', models.CharField(max_length=20, verbose_name='判词条件')),
                ('saved_by', models.CharField(max_length=64, verbose_name='存档人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_snapshot', models.CharField(max_length=200, verbose_name='存档时附言')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_hits', to='inspection.inspection')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='inspection.queryarchive')),
            ],
        ),
    ]
